// File: /components/typography/index.ts
export { H1 } from "./h1";
export { H2 } from "./h2";
export { H3 } from "./h3";
export { H4 } from "./h4";
export { P } from "./p";
export { A } from "./a";
export { Blockquote } from "./blockquote";
export { UL } from "./ul";
export { OL } from "./ol";
export { LI } from "./li";
export { Code } from "./code";
export { Lead } from "./lead";
export { Large } from "./large";
export { Small } from "./small";
export { Muted } from "./muted";
export { HR } from "./hr";
export { Callout } from "./callout";
export { Snippet } from "./snippet";
export { Figure } from "./figure";
export { Caption } from "./caption";
export { FootNotes, Ref, FootNote } from "./footnotes";
